import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { AuthContextProvider } from "./context/AuthContext";
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/components/theme-provider";

import 'prismjs/themes/prism.css';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="google-signin-client_id" content="645686121121-5levjhqrpeg472h47ct3la2a8t96bt4j.apps.googleusercontent.com"/>
      <body>
        <SessionProvider>
          <AuthContextProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              disableTransitionOnChange
            >
                {children}
        
              <Toaster />
            </ThemeProvider>
          </AuthContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}